"""Wire-compat golden vectors shared with the TypeScript ``@bolthub/pay``.

``tests/fixtures/tpp_vectors.json`` was generated by running the REAL TS
implementation (``packages/pay/src/token.ts``), and the TS suite asserts
against the same file (``packages/pay/src/__tests__/tpp-vectors.test.ts``), so
neither implementation can drift from the other silently.
"""

import json
from pathlib import Path

import pytest

from bolthub import (
    PAYMENT_META_KEY,
    ToolClient,
    create_paywall,
    l402_payer,
    l402_rail,
    sha256_hex,
    sign_l402_token,
    verify_l402_token,
    verify_preimage,
)

FIXTURE = Path(__file__).parent / "fixtures" / "tpp_vectors.json"


@pytest.fixture(scope="module")
def vectors():
    return json.loads(FIXTURE.read_text())


class TestTokenVectors:
    def test_signing_reproduces_the_ts_token_byte_for_byte(self, vectors):
        assert (
            sign_l402_token(vectors["secret"], vectors["token"]["payload"])
            == vectors["token"]["token"]
        )

    def test_verifies_the_ts_signed_token(self, vectors):
        res = verify_l402_token(
            vectors["secret"], vectors["token"]["token"], now=vectors["verifyNow"]
        )
        assert res["ok"] is True
        assert res["payload"] == vectors["token"]["payload"]

    def test_expired_ts_token_is_rejected(self, vectors):
        expired = vectors["token"]["expired"]
        assert (
            sign_l402_token(vectors["secret"], expired["payload"]) == expired["token"]
        )
        res = verify_l402_token(vectors["secret"], expired["token"], now=vectors["verifyNow"])
        assert res == {"ok": False, "reason": expired["reason"]}

    def test_tampered_ts_token_is_rejected(self, vectors):
        tampered = vectors["token"]["tampered"]
        res = verify_l402_token(vectors["secret"], tampered["token"], now=vectors["verifyNow"])
        assert res == {"ok": False, "reason": tampered["reason"]}

    def test_preimage_payment_hash_pairs(self, vectors):
        for pair in vectors["preimages"]:
            assert verify_preimage(pair["preimage"], pair["paymentHash"]) is pair["valid"]
            if pair["valid"]:
                assert sha256_hex(pair["preimage"]) == pair["paymentHash"]


class TestChallengeAndProofVectors:
    def test_ts_proof_verifies_against_the_python_rail(self, vectors):
        challenge = vectors["challenge"]

        class UnusedInvoices:
            def create_invoice(self, amount_sat, memo):  # pragma: no cover
                raise AssertionError("verify must not mint")

        rail = l402_rail(vectors["secret"], UnusedInvoices())
        result = rail.verify(
            vectors["proof"]["proof"],
            resource=challenge["resource"],
            price=challenge["price"],
        )
        assert result == {
            "ok": True,
            "resource": challenge["resource"],
            "amount": challenge["price"]["amount"],
        }

    def test_ts_proof_scoped_to_another_resource_is_rejected(self, vectors):
        class UnusedInvoices:
            def create_invoice(self, amount_sat, memo):  # pragma: no cover
                raise AssertionError("verify must not mint")

        rail = l402_rail(vectors["secret"], UnusedInvoices())
        result = rail.verify(
            vectors["proof"]["proof"],
            resource="another_tool",
            price=vectors["challenge"]["price"],
        )
        assert result["ok"] is False
        assert result["reason"] == "proof scoped to a different resource"

    def test_challenge_to_proof_roundtrip_through_paywall_and_tool_client(self, vectors):
        """Seller mints the fixture's exact challenge; the buyer pays it with a
        stub wallet and unlocks the handler. Proof and token bytes match the
        TS-generated fixture end to end."""
        challenge_vec = vectors["challenge"]
        offer_vec = challenge_vec["offers"][0]

        class FixtureInvoices:
            def create_invoice(self, amount_sat, memo):
                assert amount_sat == offer_vec["amount"]
                return offer_vec["invoice"], vectors["token"]["payload"]["paymentHash"]

        class FixtureWallet:
            def pay_invoice(self, bolt11):
                assert bolt11 == offer_vec["invoice"]
                return vectors["preimages"][0]["preimage"]

        pay = create_paywall(rails=[l402_rail(vectors["secret"], FixtureInvoices())])
        handler = pay(
            lambda args, extra: {"content": [{"type": "text", "text": "PAID CONTENT"}]},
            price=challenge_vec["price"],
            resource=challenge_vec["resource"],
        )

        seen = {}

        def caller(meta=None):
            if meta is not None:
                seen["proof"] = meta[PAYMENT_META_KEY]
            return handler({}, {"_meta": meta} if meta else None)

        buyer = ToolClient(
            [l402_payer(FixtureWallet())], max_total={"sat": 10_000}
        )
        result = buyer.call(caller)

        assert result["content"][0]["text"] == "PAID CONTENT"
        assert "isError" not in result
        assert buyer.spent_for("sat") == challenge_vec["price"]["amount"]
        # The proof presented on retry is scheme-identical to the fixture; the
        # preimage half is byte-identical (the token half embeds a live expiry).
        assert seen["proof"]["scheme"] == vectors["proof"]["scheme"]
        assert seen["proof"]["proof"].endswith(":" + vectors["preimages"][0]["preimage"])

    def test_minted_challenge_matches_the_fixture_wire_shape(self, vectors):
        """A Python-minted challenge for the fixture inputs carries the same
        fields and wire values as the TS-minted fixture (modulo the live
        expiry, which the rail stamps from the clock)."""
        challenge_vec = vectors["challenge"]
        offer_vec = challenge_vec["offers"][0]

        class FixtureInvoices:
            def create_invoice(self, amount_sat, memo):
                return offer_vec["invoice"], vectors["token"]["payload"]["paymentHash"]

        pay = create_paywall(rails=[l402_rail(vectors["secret"], FixtureInvoices())])
        handler = pay(
            lambda args, extra: {"content": []},
            price=challenge_vec["price"],
            resource=challenge_vec["resource"],
        )
        result = handler({})
        assert result["isError"] is True
        challenge = result["_meta"][PAYMENT_META_KEY]

        assert challenge["status"] == challenge_vec["status"]
        assert challenge["version"] == challenge_vec["version"]
        assert challenge["price"] == challenge_vec["price"]
        assert challenge["resource"] == challenge_vec["resource"]
        offer = challenge["offers"][0]
        assert set(offer.keys()) == set(offer_vec.keys())
        for key in ("scheme", "amount", "asset", "invoice"):
            assert offer[key] == offer_vec[key]
        assert offer["wwwAuthenticate"] == (
            f'L402 macaroon="{offer["token"]}", invoice="{offer["invoice"]}"'
        )
        # The freshly minted token verifies and is scoped like the fixture's.
        res = verify_l402_token(vectors["secret"], offer["token"])
        assert res["ok"] is True
        assert res["payload"]["paymentHash"] == vectors["token"]["payload"]["paymentHash"]
        assert res["payload"]["resource"] == challenge_vec["resource"]
