/**
 * Wire-compat golden vectors shared with the Python `bolthub` package.
 *
 * The fixture lives in `packages/agent-python/tests/fixtures/tpp_vectors.json`
 * and is asserted by BOTH this suite and the Python one
 * (`tests/test_tpp_vectors.py`), so neither implementation can drift from the
 * TPP wire format silently. The vectors were generated by this package's
 * `signL402Token` / `sha256Hex`.
 */

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { l402Rail } from "../rails/l402";
import { sha256Hex, signL402Token, verifyL402Token, verifyPreimage } from "../token";
import type { L402TokenPayload } from "../token";
import type { PaymentChallenge } from "../types";

interface TppVectors {
  secret: string;
  verifyNow: number;
  token: {
    payload: L402TokenPayload;
    token: string;
    expired: { payload: L402TokenPayload; token: string; reason: string };
    tampered: { token: string; reason: string };
  };
  preimages: { preimage: string; paymentHash: string; valid: boolean }[];
  challenge: PaymentChallenge;
  proof: { scheme: string; proof: string };
}

const vectors: TppVectors = JSON.parse(
  readFileSync(
    join(import.meta.dir, "../../../agent-python/tests/fixtures/tpp_vectors.json"),
    "utf8",
  ),
);

describe("TPP golden vectors (shared with the Python SDK)", () => {
  test("signing reproduces the fixture token byte-for-byte", () => {
    expect(signL402Token(vectors.secret, vectors.token.payload)).toBe(vectors.token.token);
    expect(signL402Token(vectors.secret, vectors.token.expired.payload)).toBe(
      vectors.token.expired.token,
    );
  });

  test("the fixture token verifies at the fixture clock", () => {
    const res = verifyL402Token(vectors.secret, vectors.token.token, vectors.verifyNow);
    expect(res.ok).toBe(true);
    if (res.ok) expect(res.payload).toEqual(vectors.token.payload);
  });

  test("the expired fixture token is rejected", () => {
    const res = verifyL402Token(vectors.secret, vectors.token.expired.token, vectors.verifyNow);
    expect(res).toEqual({ ok: false, reason: vectors.token.expired.reason });
  });

  test("the tampered fixture token is rejected", () => {
    const res = verifyL402Token(vectors.secret, vectors.token.tampered.token, vectors.verifyNow);
    expect(res).toEqual({ ok: false, reason: vectors.token.tampered.reason });
  });

  test("preimage/paymentHash pairs", () => {
    for (const pair of vectors.preimages) {
      expect(verifyPreimage(pair.preimage, pair.paymentHash)).toBe(pair.valid);
      if (pair.valid) expect(sha256Hex(pair.preimage)).toBe(pair.paymentHash);
    }
  });

  test("the fixture proof verifies against the l402 rail", async () => {
    const rail = l402Rail({
      secret: vectors.secret,
      invoiceProvider: {
        createInvoice: async () => {
          throw new Error("verify must not mint");
        },
      },
    });
    const result = await rail.verify(vectors.proof.proof, {
      resource: vectors.challenge.resource,
      price: vectors.challenge.price,
    });
    expect(result).toEqual({
      ok: true,
      resource: vectors.challenge.resource,
      amount: vectors.challenge.price.amount,
    });
  });

  test("the fixture proof is scoped: another resource is rejected", async () => {
    const rail = l402Rail({
      secret: vectors.secret,
      invoiceProvider: {
        createInvoice: async () => {
          throw new Error("verify must not mint");
        },
      },
    });
    const result = await rail.verify(vectors.proof.proof, {
      resource: "another_tool",
      price: vectors.challenge.price,
    });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe("proof scoped to a different resource");
  });

  test("the fixture challenge matches this implementation's wire shape", () => {
    const offer = vectors.challenge.offers[0];
    expect(vectors.challenge.status).toBe("payment_required");
    expect(vectors.challenge.version).toBe("0.1");
    expect(offer.scheme).toBe("l402");
    expect(offer.token).toBe(vectors.token.token);
    expect(offer.wwwAuthenticate).toBe(
      `L402 macaroon="${offer.token}", invoice="${offer.invoice}"`,
    );
  });
});
